# -*- coding: utf-8 -*-
"""hangman_visual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5aWGgqkaMp1iK2jq4yRBO5WO9ly5UbA
"""

lives_visual_dict = {
        0: """
                ___________
               | /        |
               |/        ( )
               |          |
               |         / \\
               |
           """,
        1: """
                ___________
               | /        |
               |/        ( )
               |          |
               |         /
               |
            """,
        2: """
                ___________
               | /        |
               |/        ( )
               |          |
               |
               |
            """,
        3: """
                ___________
               | /        |
               |/        ( )
               |
               |
               |
            """,
        4: """
                ___________
               | /        |
               |/
               |
               |
               |
            """,
        5: """
                ___________
               | /
               |/
               |
               |
               |
            """,
        6: """
               |
               |
               |
               |
               |
            """,
        7: "",
    }