# -*- coding: utf-8 -*-
"""Hangman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOTvtMxes22HV5wXvCsrWB_UHt9uEQAc
"""

import random
from data import word
import string
from hangman_visual import lives_visual_dict


def get_valid_word(words):
  word = random.choice(words)

  #checking weather the word is valid to be guessed or not
  while "-" in word or " " in word:
    word = random.choice(words)

  return word.upper()



def hangman():
  word = get_valid_word(words)
  used_letters = set()
  word_letters = set(word)
  lives = 7
  alphabets = set(string.ascii_uppercase)



  while len(word_letters) > 0 and lives > 0 :
    print(f"You have {lives} lives left and you have used these letters: {' '.join(used_letters)}")

    word_list = [letters if letters in used_letters else '-' for letters in word]
    print(lives_visual_dict[lives])
    print("Current word: " ,  " ".join(word_list))
    print("\n")



    user_input = input("Guess the letter: ").upper()
    if user_input in alphabets - used_letters:
      used_letters.add(user_input)
      if user_input in word_letters:
        word_letters.remove(user_input)

      else:
        lives = lives - 1
        print(f"{user_input} is not in the word.")

    elif user_input in used_letters:
      print("You have already used this letter. please try again.")

    else:
      print("Invalid letter. Please try again.")


  #out of while loop

  if lives == 0:
    print(lives_visual_dict[lives])
    print("You died, sorry. The word was", word)
  else:
    print(f"Yay! You guessed the word, {word} !!")


if __name__ == "__main__":
  hangman()