# -*- coding: utf-8 -*-
"""Guess_the_number_game_python_project(computer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147jSGNVNYAF38qTvVu3m2fwlndcXlIkF
"""

import random
def main():
  random_number : int = random.randint(1,100)
  print("I am thihking of a number between 1 to 100")
  guess : int = int(input("Enter a number: "))

  while True:
    if guess < random_number:
      print("Too low")
      guess = int(input("Enter new number: "))

    elif guess >  random_number:
      print("Too high")
      guess = int(input("Enter new number: "))

    else:
      print(f"Congrat's you have guessed the number {random_number}")
      break

if __name__ == "__main__":
  main()