# -*- coding: utf-8 -*-
"""Rock_paper_scissor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OipiqTLavWYrAx8JruEF-3ybaMW-bbU
"""

import random

def play():
  while True:
    user = input("What's your choice? 'r' for 'rock' 'p' for 'paper' and 's' for scissor: ").lower()
    computer = random.choice(['r','p','s'])

    if user == '':
      break

    if user not in ['r','p','s']:
      print("Invalid Input")
      continue

    if user == computer:
      print("It's a tie")
      continue

    if iswin(user,computer):
      print("You Won!!")
    else:
      print("You Lost!!")

def iswin(player,opponent):

  if(player == 'r' and opponent == 's' or player == 's' and opponent == 'p' or player == 'p' and opponent == 'r'):
    return True

if __name__ == '__main__':
  play()